"""support multiple items per order

Revision ID: e8af994ab63b
Revises: 
Create Date: 2025-07-26 23:21:10.714298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8af994ab63b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'form')
    op.drop_column('orders', 'crystal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('crystal', sa.VARCHAR(), nullable=False))
    op.add_column('orders', sa.Column('form', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
